apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: insecure-reveal-env-variables-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: insecure-reveal-env-variables-repository
  filterTags:
    pattern: '^main+-(?P<ts>.*)-[a-fA-F0-9]'
    extract: '$ts'
  policy:
     numerical:
      order: asc